version: '3.8'
services:
  db:
    image: 'postgres:13'
    restart: always
    environment:
      POSTGRES_DB: postgres        
      POSTGRES_USER: postgres          
      POSTGRES_PASSWORD: postgres  
    volumes:
      - hackyx-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
volumes:
  hackyx-data:
